Vagrant.configure("2") do |config|

  # ========= VM DATABASE =========
  config.vm.define "db" do |db|
    db.vm.hostname = "db-server"
    db.vm.box = "bento/debian-13"
    
    db.vm.network "private_network", ip: "192.168.56.11"

    db.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end

    db.vm.provision "shell", path: "provision-db.sh"
  end

  # ========= VM WEB =========
  config.vm.define "web" do |web|
    web.vm.hostname = "web-server"
    web.vm.box = "bento/debian-13"

    web.vm.network "private_network", ip: "192.168.56.10"
    web.vm.network "forwarded_port", guest: 80, host: 8080

    web.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end

    web.vm.synced_folder "./shared", "/var/www/html",
      owner: "www-data",
      group: "www-data",
      mount_options: ["dmode=755", "fmode=644"]

    web.vm.provision "shell", path: "provision-web.sh"
  end
end
