Vagrant.configure("2") do |config|

  # Box Debian 13
  config.vm.box = "bento/debian-13"

  # Hostname de la VM
  config.vm.hostname = "lamp-server"

  # Port forwarding : hôte 7676 → VM 80
  config.vm.network "forwarded_port", guest: 80, host: 7676, auto_correct: true

  # Dossier partagé
  config.vm.synced_folder "./shared",
                          "/var/www/html",
                          owner: "www-data",
                          group: "www-data",
                          mount_options: ["dmode=755,fmode=644"]

  # Provider VirtualBox
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
    vb.name = "lamp-server"
  end

  # Provisionnement (script séparé)
  config.vm.provision "shell", path: "provision.sh"

end
