Vagrant.configure("2") do |config|
  # Box demandée
  config.vm.box = "bento/debian-13"

  # Nom de la machine
  config.vm.hostname = "debian-base"

  # Réseau privé avec IP fixe
  config.vm.network "private_network", ip: "192.168.56.10"

  # Provider VirtualBox : RAM + CPU
  config.vm.provider "virtualbox" do |vb|
    vb.name = "debian-base"
    vb.memory = 1024
    vb.cpus = 1
  end

  # Provisionnement : message personnalisé dans le MOTD
  config.vm.provision "shell", inline: <<-SHELL
    echo "VM TP – Debian Base" | sudo tee /etc/motd
  SHELL
end
